// src/types/gift.types.ts

export enum RewardTier {
    COMMON = 'COMMON',
    RARE = 'RARE',
    EPIC = 'EPIC',
    LEGENDARY = 'LEGENDARY',
}

export interface ProbabilityTier {
    multiplier: number;
    probability: number;
}

export interface GiftConfig {
    id: string; // Database UUID
    giftId: number; // Client-defined numerical ID often used for configurations
    clientId: string;
    name?: string;
    entryPrice?: number;
    targetRtpPercent?: number;
    probabilityTable?: ProbabilityTier[];

    // Legacy single-tier fields fallback
    tier?: RewardTier;
    probability?: number;
    rewardName?: string;
    rewardValue?: number;
    inventory?: number;

    isActive: boolean;
    createdAt: string;
    updatedAt: string;
}

export interface SpinResult {
    tier: RewardTier;
    rewardName: string;
    rewardValue: number;
    isWin: boolean;
}

export interface LuckyTransaction {
    id: string; // The UUID generated by frontend (idempotency key)
    clientId: string;
    userId: string;
    giftConfigId: string | null;
    spinResult: SpinResult | null;
    status: 'PENDING' | 'SUCCESS' | 'FAILED';
    createdAt: string;
}
